name: Build and Scan Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t hello-node-app:latest .

      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@v0.13.1
        with:
          scan-type: image
          image-ref: hello-node-app:latest
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

